<?php

namespace SkylarkSoft\GoRMG\HR\Exports;

use Maatwebsite\Excel\Concerns\WithMapping;
use SkylarkSoft\GoRMG\HR\Models\HrEmployee;
use SkylarkSoft\GoRMG\HR\Models\HrEmployeeOfficialInfo;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\FromCollection;

class EmployeeExport implements FromCollection, WithMapping, WithHeadings
{
    /**
     * @return \Illuminate\Support\Collection
     */

    public function headings(): array
    {
        return [
            'id',
            'unique_id',
            'first_name',
            'last_name',
            'name_bn',
            'department',
            'section',
            'designation',
            'nid',
            'date_of_birth',
            'father_name',
            'father_name_bn',
            'mother_name',
            'mother_name_bn',
            'nominee',
            'nominee_bn',
            'nominee_relation',
            'nominee_relation_bn',
            'spouse_name',
            'spouse_name_bn',
            'nationality',
            'nationality_bn',
            'marital_status',
            'present_address',
            'present_address_bn',
            'present_address_zilla_id',
            'present_address_zilla_bn_id',
            'present_address_village',
            'present_address_village_bn',
            'present_address_upazilla_id',
            'present_address_upazilla_bn_id',
            'present_address_post_office_id',
            'present_address_post_office_bn',
            'present_address_post_code_id',
            'present_address_post_code_bn',
            'blood_group',
            'birth_certificate_no',
            'acne_details',
            'acne_details_bn',
            'height',
            'lawful_guardian',
            'lawful_guardian_bn',
            'religion',
            'religion_bn',
            'permanent_address',
            'permanent_address_bn',
            'zilla_id',
            'zilla_bn_id',
            'village',
            'village_bn',
            'upazilla_id',
            'upazilla_bn_id',
            'post_office_id',
            'post_office_bn',
            'post_code_id',
            'post_code_bn',
            'physical_appearance',
            'acne',
            'beard',
            'mustache',
            'bank_info',
            'branch',
            'account',
            'tin',
            'basic_salary',
            'transport_allowance',
            'house_rent',
            'medical_allowance',
            'food_allowance',
            'sex',
            'photo',
            'emergency_contact_no_bn',
            'employee_id',
            'machine_id',
            'mobile_no',
            'mobile_no_bn',
            'reference_id',
            'source',
            'factory_id',
            'work_type_id',
            'group_id',
            'grade_id',
            'code',
            'type',
            'bgmea_id',
            'punch_card_id',
            'date_of_joining',
            'job_permanent_date',
            'date_of_joining_bn',
            'bank_id',
            'account_no',
            'reporting_to',
            'shift_enabled',
            'termination_date',

        ];
    }

    public function collection()
    {
        $employee = HrEmployee::query()
            ->with([
                'employeeOfficialInfo.departmentDetails',
                'employeeOfficialInfo.sectionDetails',
                'employeeOfficialInfo.designationDetails',
                'zilla',
                'upazilla',
                'postOfice',
                'presentAdressZilla',
                'presentAdressUpazilla',
                'presentAdressPostOffice',
            ])->get();

        return $employee;
    }

    public function map($collection): array
    {
        return [
            'id' => $collection->id,
            'unique_id' => $collection->unique_id,
            'first_name' => $collection->first_name,
            'last_name' => $collection->last_name,
            'name_bn' => $collection->name_bn,
            'department_id' => $collection->employeeOfficialInfo->departmentDetails->name,
            'section_id' => $collection->employeeOfficialInfo->sectionDetails->name,
            'designation_id' => $collection->employeeOfficialInfo->designationDetails->name,
            'nid' => $collection->nid,
            'date_of_birth' => $collection->date_of_birth,
            'father_name' => $collection->father_name,
            'father_name_bn' => $collection->father_name_bn,
            'mother_name' => $collection->mother_name,
            'mother_name_bn' => $collection->mother_name_bn,
            'nominee' => $collection->nominee,
            'nominee_bn' => $collection->nominee_bn,
            'nominee_relation' => $collection->nominee_relation,
            'nominee_relation_bn' => $collection->nominee_relation_bn,
            'spouse_name' => $collection->spouse_name,
            'spouse_name_bn' => $collection->spouse_name_bn,
            'nationality' => $collection->nationality,
            'nationality_bn' => $collection->nationality_bn,
            'marital_status' => $collection->marital_status,
            'present_address' => $collection->present_address,
            'present_address_bn' => $collection->present_address_bn,
            'present_address_zilla_id' => $collection->presentAdressZilla->name,
            'present_address_zilla_bn_id' => $collection->presentAdressZilla->name_bn,
            'present_address_village' => $collection->present_address_village,
            'present_address_village_bn' => $collection->present_address_village_bn,
            'present_address_upazilla_id' => $collection->presentAdressUpazilla->name,
            'present_address_upazilla_bn_id' => $collection->presentAdressUpazilla->name_bn,
            'present_address_post_office_id' => $collection->presentAdressPostOffice->postOffice,
            'present_address_post_office_bn' => $collection->present_address_post_office_bn,
            'present_address_post_code_id' => $collection->present_address_post_code_id,
            'present_address_post_code_bn' => $collection->present_address_post_code_bn,
            'blood_group' => $collection->blood_group,
            'birth_certificate_no' => $collection->birth_certificate_no,
            'acne_details' => $collection->acne_details,
            'acne_details_bn' => $collection->acne_details_bn,
            'height' => $collection->height,
            'lawful_guardian' => $collection->lawful_guardian,
            'lawful_guardian_bn' => $collection->lawful_guardian_bn,
            'religion' => $collection->religion,
            'religion_bn' => $collection->religion_bn,
            'permanent_address' => $collection->permanent_address,
            'permanent_address_bn' => $collection->permanent_address_bn,
            'zilla_id' => $collection->zilla->name,
            'zilla_bn_id' => $collection->zilla->name_bn,
            'village' => $collection->village,
            'village_bn' => $collection->village_bn,
            'upazilla_id' => $collection->upazilla->name,
            'upazilla_bn_id' => $collection->upazilla->name_bn,
            'post_office_id' => $collection->postOfice->postOfice,
            'post_office_bn' => $collection->post_office_bn,
            'post_code_id' => $collection->post_code_id,
            'post_code_bn' => $collection->post_code_bn,
            'physical_appearance' => $collection->physical_appearance,
            'acne' => $collection->acne,
            'beard' => $collection->beard,
            'mustache' => $collection->mustache,
            'bank_info' => $collection->bank_info,
            'branch' => $collection->branch,
            'account' => $collection->account,
            'tin' => $collection->tin,
            'basic_salary' => $collection->basic_salary,
            'transport_allowance' => $collection->transport_allowance,
            'house_rent' => $collection->house_rent,
            'medical_allowance' => $collection->medical_allowance,
            'food_allowance' => $collection->food_allowance,
            'sex' => $collection->sex,
            'photo' => $collection->photo,
            'emergency_contact_no_bn' => $collection->emergency_contact_no_bn,
            'employee_id' => $collection->employee_id,
            'machine_id' => $collection->machine_id,
            'mobile_no' => $collection->mobile_no,
            'mobile_no_bn' => $collection->mobile_no_bn,
            'reference_id' => $collection->reference_id,
            'source' => $collection->source,
            'factory_id' => $collection->factory_id,
            'work_type_id' => $collection->employeeOfficialInfo->work_type_id,
            'group_id' => $collection->employeeOfficialInfo->group_id,
            'grade_id' => $collection->employeeOfficialInfo->grade_id,
            'code' => $collection->employeeOfficialInfo->code,
            'type' => $collection->employeeOfficialInfo->type,
            'bgmea_id' => $collection->employeeOfficialInfo->bgmea_id,
            'punch_card_id' => $collection->employeeOfficialInfo->punch_card_id,
            'date_of_joining' => $collection->employeeOfficialInfo->date_of_joining,
            'job_permanent_date' => $collection->employeeOfficialInfo->job_permanent_date,
            'date_of_joining_bn' => $collection->employeeOfficialInfo->date_of_joining_bn,
            'bank_id' => $collection->employeeOfficialInfo->bank_id,
            'account_no' => $collection->employeeOfficialInfo->account_no,
            'reporting_to' => $collection->employeeOfficialInfo->reporting_to,
            'shift_enabled' => $collection->employeeOfficialInfo->shift_enabled,
            'termination_date' => $collection->employeeOfficialInfo->termination_date,
        ];
    }
}
